name: Set up macOS env for building IFS master

on:
  pull_request:
    branch:
      - master
  push:
    branch:
      - master

jobs:
  ci:
    strategy:
      matrix:
        os: [macos-11, macos-12]
        python-version: [3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pyyaml ruamel.yaml
      - name: Install other dependencies
        run: |
          # Coreutils
          brew install coreutils
          echo "$(brew --prefix)/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
          # FCM
          curl -L -O https://github.com/metomi/fcm/archive/refs/tags/2021.05.0.tar.gz
          tar xzf 2021.05.0.tar.gz
          echo "${PWD}/fcm-2021.05.0/bin" >> $GITHUB_PATH
          # Everything else
          brew install cmake openmpi gcc eigen boost fftw hdf5 netcdf
      - name: Run tests
        run: |
          PERM="${PWD}"
          export PERM
          echo "${PATH}"
          echo "${PERM}"
          fcm --version
          export CC="$(brew --prefix)/bin/gcc-11"
          export CXX="$(brew --prefix)/bin/g++-11"
          $CC -fopenmp ./omptest.c
          ./a.out
          $CXX || true

