name: Set up macOS env for building IFS master

on:
  pull_request:
    branch:
      - master
  push:
    branch:
      - master

jobs:
  ci:
    strategy:
      matrix:
        os: [macos-11, macos-12]
        python-version: [3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pyyaml ruamel.yaml
      - name: Install other dependencies
        run: |
          PERM="${PWD}"
          export PERM
          brew install coreutils
          PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:${PATH}"
          curl -L -O https://github.com/metomi/fcm/archive/refs/tags/2021.05.0.tar.gz
          tar xzf 2021.05.0.tar.gz
          PATH="${PWD}/fcm-2021.05.0/bin:${PATH}"
          export PATH
      - name: Run tests
        run: |
          sw_vers
          python --version
          brew --prefix
          ls -ld "$(brew --prefix)/opt/coreutils/libexec/gnubin"
          pwd
          echo "${PATH}"
          echo "${PERM}"
